### ISSUE TITLE
Botão "Voltar" no header deve sumir na primeira página

### ISSUE THREAD

**Issue by vcapretz** [mundipagg/artis#46]
Atualmente o Header possui um botão com o ícone da flecha de voltar para navegar para trás, mas ele fica visível mesmo na primeira página e clicar nele não gera ação nenhuma.

Seria massa se ele sumisse ou simplesmente ficasse desabilitado se não houver mais páginas para trás. 

(O mesmo acontece com o botão continuar, mas esse não é no Header)

**Comment by thiagommedeiros** [comment]
Boa! Inclusive no layout ele nao aparece mesmo!
